namespace FeatherQuilld.Utils.WebSpaces;

/// <summary>Per-site files under the WebSpace data directory (<c>.featherquilld/</c>).</summary>
public static class WebSpaceSiteFiles
{
    public const string PhpIniRelative = ".featherquilld/php.ini";
    public const string ApacheAddonsRelative = ".featherquilld/apache-addons.conf";
    public const string DbDumpsRelative = ".featherquilld/db-dumps";

    public const string DefaultPhpIni =
        """
        ; FeatherQuilld per-site php.ini (bind-mounted into the PHP container)
        memory_limit = 256M
        upload_max_filesize = 64M
        post_max_size = 64M
        max_execution_time = 120
        """;

    public static string PhpIniHostPath(string dataPath) =>
        Path.Combine(dataPath, PhpIniRelative.Replace('/', Path.DirectorySeparatorChar));

    public static string ApacheAddonsHostPath(string dataPath) =>
        Path.Combine(dataPath, ApacheAddonsRelative.Replace('/', Path.DirectorySeparatorChar));

    public static void EnsurePhpIni(string dataPath)
    {
        var path = PhpIniHostPath(dataPath);
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        if (!File.Exists(path))
            File.WriteAllText(path, DefaultPhpIni + "\n");
    }

    public static void WriteApacheAddons(string dataPath, WebSpace space)
    {
        Directory.CreateDirectory(Path.Combine(dataPath, ".featherquilld"));
        File.WriteAllText(ApacheAddonsHostPath(dataPath), BuildApacheAddonConf(space));
    }

    public static string BuildApacheAddonConf(WebSpace space)
    {
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("# Generated by FeatherQuilld per-host document roots");
        sb.AppendLine();

        IReadOnlyList<WebSpaceDomainRoute> routes = space.DomainRoutes.Count > 0
            ? space.DomainRoutes
            : space.Domains.Select((d, i) => new WebSpaceDomainRoute
            {
                Domain = d,
                Type = i == 0 ? "primary" : "alias",
            }).ToList();

        foreach (var route in routes)
        {
            if (string.Equals(route.Type, "redirect", StringComparison.OrdinalIgnoreCase))
                continue;
            if (string.IsNullOrWhiteSpace(route.Domain))
                continue;

            var rel = !string.IsNullOrWhiteSpace(route.DocumentRoot)
                ? route.DocumentRoot.Trim().Trim('/')
                : (space.DocumentRoot ?? "").Trim().Trim('/');
            var doc = string.IsNullOrEmpty(rel) ? "/var/www/html" : "/var/www/html/" + rel;

            sb.AppendLine("<VirtualHost *:80>");
            sb.AppendLine($"  ServerName {route.Domain}");
            sb.AppendLine($"  DocumentRoot {doc}");
            sb.AppendLine($"  <Directory {doc}>");
            sb.AppendLine("    Options FollowSymLinks");
            sb.AppendLine("    AllowOverride All");
            sb.AppendLine("    Require all granted");
            sb.AppendLine("  </Directory>");
            sb.AppendLine("</VirtualHost>");
            sb.AppendLine();
        }

        return sb.ToString();
    }
}
